# Generated by Django 2.2.4 on 2019-08-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_auto_20190829_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipform',
            name='internShipWebSite',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
