# Generated by Django 2.2.4 on 2019-09-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_internshipplace_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='student',
        ),
    ]
