# Generated by Django 2.2.4 on 2019-09-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_auto_20190908_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(default='Internship', max_length=31),
        ),
    ]
