# Generated by Django 2.2.4 on 2019-09-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_remove_request_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='agreementUploadedUrl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='internShipConfirmation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
