# Generated by Django 2.2.4 on 2019-08-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_auto_20190831_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipform',
            name='emailIH',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipform',
            name='nameIH',
            field=models.CharField(default=' ', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipform',
            name='phoneIH',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='term',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Summer')], max_length=15),
        ),
        migrations.AlterField(
            model_name='internshiphead',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
