# Generated by Django 2.2.4 on 2019-08-22 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseAdvisorTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorTeacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.Teachers')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseGuideTeacherByDH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmedguideteacher', models.CharField(max_length=31)),
                ('confirmationdate', models.DateTimeField()),
                ('departmenthead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.DepartmentHead')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseGuideTeacherByStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideTeacher1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CGTBguideteacher1', to='internship.Teachers')),
                ('guideTeacher2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CGTBguideteacher2', to='internship.Teachers')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseJudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmenthead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.DepartmentHead')),
                ('judgeTeacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.Teachers')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvalData', models.DateTimeField()),
                ('approvalStatus', models.IntegerField()),
                ('approvalAttachments', models.TextField()),
                ('departmentHead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.DepartmentHead')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='FirstJudgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingNeeded', models.BooleanField()),
                ('reportCorrection', models.BooleanField()),
                ('acceptance', models.BooleanField()),
                ('confirmationDate', models.DateTimeField()),
                ('judgeConfirmation', models.BooleanField()),
                ('judgeTeacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.Teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideTeacherAccept', models.BooleanField()),
                ('judgmentDate', models.DateTimeField()),
                ('grade', models.FloatField()),
                ('gradeText', models.TextField()),
                ('degree', models.CharField(choices=[('degree1', 'a'), ('degree1', 'b'), ('degree1', 'c'), ('degree1', 'e'), ('degree1', 'f'), ('degree1', 'g')], max_length=2)),
                ('acceptanceStatus', models.BooleanField()),
                ('attachmenturl', models.TextField()),
                ('projectStatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=3)),
                ('numberOfGuideTeacher', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportDate', models.DateTimeField()),
                ('weekNumber', models.IntegerField()),
                ('reportTitle', models.CharField(max_length=63)),
                ('reportAttachmentUploadUrl', models.TextField()),
                ('reportText', models.TextField()),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideTeacherConfirmation', models.BooleanField()),
                ('guideTeacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.ChooseGuideTeacherByStudent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('firstJudgment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.FirstJudgment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Criterion')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.TextField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.Student')),
                ('projectForm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.ProjectForm')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishTitle', models.TextField()),
                ('persionTitle', models.TextField()),
                ('description', models.TextField()),
                ('projectOutputDescription', models.TextField()),
                ('guideTeacherConfirmation', models.BooleanField()),
                ('advisorTeacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PFadvisorteacher', to='project.ChooseAdvisorTeacher')),
                ('guideTeacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PFguideteacher', to='project.ChooseGuideTeacherByDH')),
                ('projectForm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.ProjectForm')),
                ('projectKeywords', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.ProjectKeywords')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUploadURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project')),
            ],
        ),
        migrations.AddField(
            model_name='projectform',
            name='guideTeacher1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PFguideteacher1', to='project.WaitingQueue'),
        ),
        migrations.AddField(
            model_name='projectform',
            name='guideTeacher2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PFguideteacher2', to='project.WaitingQueue'),
        ),
        migrations.AddField(
            model_name='projectform',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PFstudent', to='internship.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='advisorTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProadvisorTeacher', to='project.ProposalForm'),
        ),
        migrations.AddField(
            model_name='project',
            name='guideTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProguideTeacher', to='project.ProposalForm'),
        ),
        migrations.AddField(
            model_name='project',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Projudge', to='project.ChooseJudge'),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Prostudent', to='project.ConfirmationProposal'),
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seenDate', models.DateTimeField()),
                ('opinion', models.TextField()),
                ('opinionDate', models.DateTimeField()),
                ('opinionText', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.Student')),
            ],
        ),
        migrations.AddField(
            model_name='firstjudgment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('firstJudgment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.FirstJudgment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Criterion')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhConfirmationDate', models.DateTimeField()),
                ('dhConfirmation', models.BooleanField()),
                ('departmentHead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.DepartmentHead')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationWaitingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideTeacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.WaitingQueue')),
                ('guideTeacherOpinion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Opinions')),
            ],
        ),
        migrations.AddField(
            model_name='confirmationproposal',
            name='projectForm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.ProjectForm'),
        ),
        migrations.AddField(
            model_name='confirmationproposal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.Student'),
        ),
        migrations.AddField(
            model_name='choosejudge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project'),
        ),
        migrations.AddField(
            model_name='chooseguideteacherbystudent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CGTBproject', to='project.ProjectForm'),
        ),
        migrations.AddField(
            model_name='chooseguideteacherbystudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CGTBstudent', to='internship.Student'),
        ),
        migrations.AddField(
            model_name='chooseguideteacherbydh',
            name='projectform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.ProjectForm'),
        ),
        migrations.AddField(
            model_name='chooseadvisorteacher',
            name='projectForm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.ProjectForm'),
        ),
        migrations.AddField(
            model_name='chooseadvisorteacher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internship.Student'),
        ),
    ]
