# Generated by Django 2.2.4 on 2019-09-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='role',
            new_name='role_id',
        ),
    ]
