# Generated by Django 2.2.4 on 2019-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('DepartmentHead', 'DepartmentHead'), ('FacultyTrainingStaff', 'FacultyTrainingStaff'), ('UniversityTrainingStaff', 'UniversityTrainingStaff'), ('InternshipHead', 'InternshipHead')], max_length=31),
        ),
    ]
