# Generated by Django 2.2.4 on 2019-09-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20190903_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='role_id',
            new_name='roles',
        ),
    ]
