# Generated by Django 2.2.4 on 2019-09-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20190905_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
