# Generated by Django 2.2.4 on 2019-09-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20190905_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='public.Role'),
        ),
    ]
