# Generated by Django 2.2.4 on 2019-08-22 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Faculties')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faTitle', models.TextField()),
                ('enTitle', models.TextField()),
                ('timeRunMonth', models.IntegerField()),
                ('dateSuggestion', models.IntegerField()),
                ('goals', models.TextField()),
                ('reason', models.TextField()),
                ('interdisciplinary', models.TextField()),
                ('departmentGoals', models.CharField(max_length=63)),
                ('departmentApproval', models.CharField(choices=[('1', 'accepted'), ('2', 'rejected'), ('3', 'unverified')], max_length=2)),
                ('departmentDateApproval', models.DateTimeField(auto_now_add=True)),
                ('facultyApproval', models.CharField(choices=[('1', 'accepted'), ('2', 'rejected'), ('3', 'unverified')], max_length=2)),
                ('facultyDateApproval', models.DateTimeField(auto_now_add=True)),
                ('collegeApproval', models.CharField(choices=[('1', 'accepted'), ('2', 'rejected'), ('3', 'unverified')], max_length=2)),
                ('collegeDateApproval', models.DateTimeField(auto_now_add=True)),
                ('universityApproval', models.CharField(choices=[('1', 'accepted'), ('2', 'rejected'), ('3', 'unverified')], max_length=2)),
                ('universityDateApproval', models.DateTimeField(auto_now_add=True)),
                ('Institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Institute')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.College')),
                ('collegeSignatureApproval', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Progcollegesignatureapproval', to=settings.AUTH_USER_MODEL)),
                ('departmentSignatureApproval', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Progdepartmentsignatureapproval', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Faculties')),
                ('facultySignatureApproval', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Progfacultysignatureapproval', to=settings.AUTH_USER_MODEL)),
                ('universitySignatureApproval', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Proguniversitysignatureapproval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('title', models.TextField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='research.Programs')),
            ],
        ),
        migrations.CreateModel(
            name='Expected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='research.Programs')),
            ],
        ),
        migrations.CreateModel(
            name='Enforcers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.IntegerField()),
                ('fullName', models.CharField(max_length=127)),
                ('rank', models.IntegerField()),
                ('dutyDescribtion', models.TextField()),
                ('workPhone', models.CharField(max_length=31)),
                ('mobile', models.CharField(max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='research.Major')),
                ('serviceLocation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='research.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Faculties')),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondingMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('enforcers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='research.Enforcers')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Programs')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Faculties'),
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Programs')),
            ],
        ),
    ]
